version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: carsa-server
    restart: on-failure
    ports:
      - '3000:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: carsa-client
    ports:
      - '3001:80'
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
    depends_on:
      - backend

  postgres:
    ports:
      - "6434: 5432"
    image: postgres:alpine
    container_name: carsa-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./frontend/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_HOST: 127.0.0.1
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: carsa-redis
    command: redis-server --save 60 1 --maxmemory 512mb --maxmemory-policy allkeys-lru --loglevel warning
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  db_data:
  cache:
  logs:
