version: '3.9'

services:
  backend:
    image: volex/carsa-server
    container_name: carsa-server
    restart: on-failure
    ports:
      - '3000:8080'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    image: volex/carsa-client
    command: "serve -s build -n -p 3001"
    container_name: carsa-client
    ports:
      - '3001:3001'
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
    depends_on:
      - backend

  postgres:
    image: postgres:alpine
    container_name: carsa-postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:alpine
    container_name: carsa-redis
    command: redis-server --save 60 1 --maxmemory 512mb --maxmemory-policy allkeys-lru --loglevel warning
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  db_data:
  cache:
  logs:
